### ISSUE TITLE
is there a full version of it? fun game!

### ISSUE THREAD

**Issue by zzz6519003** [securas/Daemon-vs-Demon#21]

**Comment by securas** [comment]
This is it for now... Sorry... We might extend it for the future though.

On Dec 31, 2017 22:00, "Snowmanzzz(Zhengzhong Zhao)" <
notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/securas/Daemon-vs-Demon/issues/21>, or mute the thread

**Comment by zzz6519003** [comment]
Close

**Comment by simPod** [comment]
I killed like 10 demons and then there was a bridge with a hole between. Is it the end then? Playing it was awwwwww (!) but lasted only several seconds :(

**Comment by securas** [comment]
You need to try harder

**Comment by simPod** [comment]
WANT. TO. SMASH. DEMONS

!

**Comment by simPod** [comment]
OMG FOUND A SWORD! 

![image](https://user-images.githubusercontent.com/327717/47887069-cee0a400-de3d-11e8-89b7-dc7a9403dd91.png)
